### ISSUE TITLE
Doesn't work well with IE11

### ISSUE THREAD

**Issue by ifthenelse** [patricktran/react-magic-slider-dots#21]
The behaviour of the plugin is not correct on Internet Explorer 11.

https://user-images.githubusercontent.com/50681/106401754-1b085d80-6426-11eb-8d0d-b1b742253571.mp4

Also, the DEMO page doesn't load at all with that browser.

**Comment by ifthenelse** [comment]
Looks like to fix it, you just need to add explicit flex properties to `.slick-dots li`
```css
.slick-dots li {
  flex-basis: auto;
  flex-shrink: 0;
  flex-grow: 0;
}
```
